# Generated by Django 4.1.7 on 2024-02-02 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilityName', models.CharField(max_length=100)),
                ('faciltyDesc', models.CharField(blank=True, max_length=255)),
                ('facilitDescExtra', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phoneNumber', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirName', models.CharField(blank=True, max_length=255)),
                ('firstName', models.CharField(blank=True, max_length=255)),
                ('telContact', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('appointmentDate', models.DateField(blank=True, null=True)),
                ('appointmentTime', models.CharField(blank=True, max_length=255)),
                ('amessage', models.TextField(max_length=255)),
            ],
            options={
                'ordering': ['-appointmentDate', '-department'],
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carouselTitle', models.CharField(blank=True, max_length=255)),
                ('carouselsubTitle', models.CharField(blank=True, max_length=255)),
                ('carouselImg', models.CharField(blank=True, max_length=255)),
                ('placeholderurl', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousels',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True, max_length=255)),
                ('mailingDate', models.DateField(auto_now_add=True)),
                ('phonecontact', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=255)),
                ('departmentDesc', models.CharField(blank=True, max_length=255)),
                ('realdept', models.BooleanField(blank=True)),
                ('departmentImg', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drname', models.CharField(blank=True, max_length=55)),
                ('drspecialty', models.CharField(blank=True, max_length=55)),
                ('drbio', models.CharField(blank=True, max_length=255)),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('drimage', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='SubscribeMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'SubscribeMail',
                'verbose_name_plural': 'SubscribeMails',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceTitle', models.CharField(max_length=50)),
                ('serviceDesc', models.CharField(max_length=255)),
                ('realserv', models.BooleanField()),
                ('logoimg', models.CharField(blank=True, max_length=255)),
                ('placeholderImg', models.CharField(blank=True, max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drcare_FE.department')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-serviceTitle', '-department'],
            },
        ),
    ]
