# Generated by Django 4.1.7 on 2024-02-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drcare_FE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phonecontact',
            field=models.CharField(max_length=15),
        ),
    ]
