# Generated by Django 5.0.1 on 2024-02-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drcare_FE', '0003_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='authorimg',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
